server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service-v1
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**
          filters:
            - RewritePath=/api/v1/users/(?<segment>.*), /api/v1/users/${segment}
        - id: company-service-v1
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/companies/**
          filters:
            - RewritePath=/api/v1/companies/(?<segment>.*), /api/v1/companies/${segment}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
