server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service-v1
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/api/v1/users/**
          filters:
            - RewritePath=/api/v1/users/(?<segment>.*), /api/v1/users/${segment}
        - id: company-service-v1
          uri: ${COMPANY_SERVICE_URL}
          predicates:
            - Path=/api/v1/companies/**
          filters:
            - RewritePath=/api/v1/companies/(?<segment>.*), /api/v1/companies/${segment}
eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
    instance:
      prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web: INFO
