server:
  port: ${USER_SERVICE_APP_PORT}
  servlet:
    context-path: /api/v1
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${USERS_DB_HOST}:${USERS_DB_PORT}/${USERS_DB_NAME}
    username: ${USERS_DB_USER}
    password: ${USERS_DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
      locations: classpath:db/migration
      baseline-on-migrate: true               
      validate-on-migrate: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
      # instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true